### ISSUE TITLE
Rotate a layer to any angle. Can it be done?

### ISSUE THREAD

**Issue by MRjimbob81** [mertyGit/SIL#1]
Hello, 

First of all, thanks for releasing your library code. I'm finding it useful for developing on an embedded device with output to the framebuffer. Development is sped up via coding on a PC and using the X11 display option.

I've a question relating to the layers and if its possible to rotate one or multiple layers around a fixed x,y point - to any given degree. (or x,y coordinate)
eg: I wish to load a PNG image of a speedo gauge needle to a layer and have that layer rotate as a variable increases/decreases 

I've so far found and experimented with a couple of functions while trawling through the code for answers but yet to find the right function. I think from reading the code comments that *sil_resizeLayer()* is designed for this but I have yet to make it work successfully. 
**quote:**
>/*****************************************************************************
> Resize layer (used for cropping and _**turning**_) will create a temporary framebuffer
>
> In: Layer context x,y top left within layer + width & height of view
> *****************************************************************************/

It's taken a lot of time to produce any usable code due to having to find the functions in different code files and understand what they do. I see you've started a Wiki page but with so many functions to write up about, it may take a while to get the documentation done :-)

Any help with the above question would be much appreciated.

**Comment by mertyGit** [comment]
Hey thanks ! Sorry I didn't see you comment faster. The "turning" I mentioned in the code remarks was turning it in steps of 90 degrees and this function should be called internally before such turning should take place. However, I removed the code for that because I couldn't see much use of it. However, I think what you want / describe is _rotating_ an image. That is (much) more complicated (if you don't rely on openGL or SDL) but interesting challenge :) Wat you can do is draw a line on a separate layer above, but you might to do some calculations yourself and doesn't look good as a "real" needle in your example. I see your point and will check it out if I can make something without difficult calculations (I try to prevent using Sin() or Cos() calls) and memory usage. But maybe using line drawing algorithm for rotating the whole picture line-by-line is an option...
I will come back on it, keep an eye on updates...

**Comment by MRjimbob81** [comment]
>  Hey thanks ! Sorry I didn't see you comment faster.

No worries there.

> I think what you want / describe is rotating an image.

Yes that is correct. An image on a particular layer.

> Wat you can do is draw a line on a separate layer above, but you might to do some calculations yourself and doesn't look good as a "real" needle in your example.

I've had a play with this idea previously. It works but the esthetics aren't that great. anti-aliased draw line looks the best for me.

I've had an attempt (read many attempts) at rotating an image on the layer all relying on COS() and SIN() with varying degrees of success - excuse the pun. Here is some hacked together function that I've been experimenting with:

```
void rotateLayer(SILLYR *layer, UINT angle)
{
    UINT width= layer->view.width;
    UINT height= layer->view.height;
    BYTE red,green,blue,alpha;

    double sinx = sin((angle)/180.0 * M_PI);  // -degrees
    double cosx = cos((angle)/180.0 * M_PI);

    int xCenter = 108; // height/2;        // Rotate image by its center. CURRENTLY USING A FIXED X,Y LOCATION!!! [10/9/2021]
    int yCenter = 125; // width/2;

    for(int x=0; x<width; x++) {
        double xt_cosx = (x-xCenter)*cosx;
        double xt_sinx = (x-xCenter)*sinx;
        for(int y=0; y<height; y++) {
            int xRotate = round(xt_cosx - ((y-yCenter)*sinx)) + xCenter;
            int yRotate = round(((y-yCenter)*cosx) + xt_sinx) + yCenter;

            if( (xRotate >= 0) && (xRotate < width) && (yRotate >= 0) && (yRotate < height) ) {
    			sil_getPixelLayer(layer,xRotate,yRotate,&red,&green,&blue,&alpha);
    			sil_putPixelLayer(layer,x,y,red,green,blue,alpha);
            } else {
              sil_putPixelLayer(layer,x,y,0,128,0,0);
            }
        }
    }
}
```

The formula is not my own but "found" on the internet. It seems to be a common formula but written many different ways.
Some angles work well while others leave pixels on the layer or just look totally wrong.
I don't know the formula well enough to work through it in my head but I believe its designed to calculate the new pixel coordinates around a given center x,y coordinate. I've wasted a few hours already tracing through the steps trying to find out why its messing up the final coordinate location... I think I might write a small program outside of SIL and debug the function there.

As a side note: 
I've found that the layer needs to be double the image length in width and height to be able to rotate successfully else the image will go out of scale (how it did this I don't know) and the image I need to rotate (the gauge needle) is 102 long by 7 pixels high.

**Comment by mertyGit** [comment]
Well, that took more then a year... (ok was busy with other stuff, sorry) . The algorithm wasn't that good, creating lot of artifacts. Inversion of the matrix helped, but still not great. So, I found the "tripple shear - with anti aliasing" code in C++ and backported it to SIL. Works ok, but because of anti-aliasing, it will get "blurry" if you use it multiple times. So always good to set back original picture back before rotating it to different angle.  

sil_rotateLayer(layer,angle) is now added to SIL
